export const communityParticipants = [
  {
    id: "u-alia",
    name: "Алия Юсупова",
    avatarKey: "AY",
    avatarEmoji: "🦊",
    xp: 920,
    level: 8,
    city: "Казань",
    role: "Создатель",
    weeklyMaterials: 9,
    helpfulAnswers: 14,
    helpfulMarks: 7,
    activityScore: 96,
    learningScore: 88,
    contributionScore: 92,
    bio: "Запускаю подростковые комьюнити и делаю сервисы для обучения.",
    interests: ["продукт", "соцсети", "дизайн"],
    streak: 12,
    clubIds: ["club-kazan", "club-product"],
  },
  {
    id: "u-roman",
    name: "Роман Тарасов",
    avatarKey: "RT",
    avatarEmoji: "🛠️",
    xp: 870,
    level: 8,
    city: "Москва",
    role: "Ментор",
    weeklyMaterials: 6,
    helpfulAnswers: 18,
    helpfulMarks: 9,
    activityScore: 91,
    learningScore: 74,
    contributionScore: 95,
    bio: "Помогаю ребятам собирать MVP, люблю хакатоны и короткие циклы.",
    interests: ["стартапы", "код", "флоу"],
    streak: 18,
    clubIds: ["club-moscow", "club-startups"],
  },
  {
    id: "u-milena",
    name: "Милена Ахметова",
    avatarKey: "MA",
    avatarEmoji: "🎨",
    xp: 760,
    level: 7,
    city: "Екатеринбург",
    role: "Создатель",
    weeklyMaterials: 11,
    helpfulAnswers: 12,
    helpfulMarks: 5,
    activityScore: 88,
    learningScore: 97,
    contributionScore: 84,
    bio: "Дизайню интерфейсы и учу одноклассников работать в Figma.",
    interests: ["иллюстрации", "ui", "медиа"],
    streak: 9,
    clubIds: ["club-creative", "club-product"],
  },
  {
    id: "u-danila",
    name: "Данила Корнеев",
    avatarKey: "DK",
    avatarEmoji: "🤖",
    xp: 640,
    level: 6,
    city: "Санкт-Петербург",
    role: "Новичок",
    weeklyMaterials: 5,
    helpfulAnswers: 7,
    helpfulMarks: 3,
    activityScore: 76,
    learningScore: 68,
    contributionScore: 72,
    bio: "Собираю ботов для учёбы, хочу сделать умного ассистента.",
    interests: ["автоматизация", "боты", "игры"],
    streak: 6,
    clubIds: ["club-startups"],
  },
  {
    id: "u-sofia",
    name: "София Лебедева",
    avatarKey: "SL",
    avatarEmoji: "🌿",
    xp: 590,
    level: 5,
    city: "Новосибирск",
    role: "Новичок",
    weeklyMaterials: 8,
    helpfulAnswers: 9,
    helpfulMarks: 4,
    activityScore: 83,
    learningScore: 86,
    contributionScore: 70,
    bio: "Люблю форматы learn&share, прокачиваю финансы для подростков.",
    interests: ["финансы", "трекеры", "соцпроекты"],
    streak: 10,
    clubIds: ["club-finance", "club-creative"],
  },
  {
    id: "u-makar",
    name: "Макар Журавлёв",
    avatarKey: "MJ",
    avatarEmoji: "🛹",
    xp: 550,
    level: 5,
    city: "Самара",
    role: "Новичок",
    weeklyMaterials: 7,
    helpfulAnswers: 6,
    helpfulMarks: 2,
    activityScore: 72,
    learningScore: 79,
    contributionScore: 65,
    bio: "Делаю короткие обучающие ролики, мечтаю собрать команду медиа.",
    interests: ["контент", "монтаж", "спорт"],
    streak: 5,
    clubIds: ["club-finance"],
  },
  {
    id: "u-vera",
    name: "Вера Богданова",
    avatarKey: "VB",
    avatarEmoji: "🚀",
    xp: 520,
    level: 5,
    city: "Краснодар",
    role: "Наставник",
    weeklyMaterials: 4,
    helpfulAnswers: 13,
    helpfulMarks: 6,
    activityScore: 78,
    learningScore: 70,
    contributionScore: 87,
    bio: "Помогаю ребятам ставить цели, веду разборы проектов.",
    interests: ["менторство", "soft skills", "командная работа"],
    streak: 7,
    clubIds: ["club-creative", "club-product"],
  },
  {
    id: "u-leo",
    name: "Лео Грин",
    avatarKey: "LG",
    avatarEmoji: "🦁",
    xp: 470,
    level: 4,
    city: "Минск",
    role: "Новичок",
    weeklyMaterials: 6,
    helpfulAnswers: 5,
    helpfulMarks: 2,
    activityScore: 69,
    learningScore: 73,
    contributionScore: 60,
    bio: "Учусь питчить идеи и прокачиваю питон для игр.",
    interests: ["геймдев", "питон", "питчи"],
    streak: 4,
    clubIds: ["club-startups"],
  },
];

export const clubs = [
  {
    id: "club-moscow",
    name: "NOESIS Москва",
    description: "Встречи по воскресеньям, питч-сессии и гостевые разборы продуктов.",
    city: "Москва",
    theme: "предпринимательство",
    coverColor: "linear-gradient(135deg, #6366f1, #8b5cf6)",
    memberIds: ["u-roman", "u-alia", "u-milena"],
  },
  {
    id: "club-kazan",
    name: "NOESIS Казань",
    description: "Комьюнити для тех, кто любит технологии и запуски.",
    city: "Казань",
    theme: "технологии",
    coverColor: "linear-gradient(135deg, #22c55e, #14b8a6)",
    memberIds: ["u-alia", "u-sofia"],
  },
  {
    id: "club-finance",
    name: "Финансы 16–18",
    description: "Учимся управлять деньгами, собирать подушки и инвестировать.",
    theme: "финансы",
    coverColor: "linear-gradient(135deg, #06b6d4, #0ea5e9)",
    memberIds: ["u-sofia", "u-makar"],
  },
  {
    id: "club-startups",
    name: "Стартапы и MVP",
    description: "Короткие циклы, клиенты и тестирование гипотез каждую неделю.",
    theme: "стартапы",
    coverColor: "linear-gradient(135deg, #f97316, #f43f5e)",
    memberIds: ["u-roman", "u-danila", "u-leo"],
  },
  {
    id: "club-product",
    name: "Продукт и дизайн",
    description: "Figma, UX-игры, исследования и дизайн для подростковых проектов.",
    theme: "дизайн",
    coverColor: "linear-gradient(135deg, #a855f7, #6366f1)",
    memberIds: ["u-alia", "u-milena", "u-vera"],
  },
  {
    id: "club-creative",
    name: "Креатив и медиа",
    description: "Видео, сторис, короткие форматы и сторителлинг.",
    theme: "креатив",
    coverColor: "linear-gradient(135deg, #eab308, #f59e0b)",
    memberIds: ["u-milena", "u-vera", "u-sofia"],
  },
];

export const teams = [
  {
    id: "team-aurora",
    name: "Аура",
    memberIds: ["u-alia", "u-roman", "u-leo"],
    questId: "quest-1",
  },
  {
    id: "team-stride",
    name: "Stride",
    memberIds: ["u-milena", "u-sofia", "u-makar"],
    questId: "quest-2",
  },
];

export const posts = [
  {
    id: "post-1",
    authorId: "u-alia",
    clubId: "club-product",
    createdAt: "2024-02-12T10:00:00.000Z",
    type: "achievement",
    title: "Дизайн-спринт закрыт",
    content: "Собрали прототип приложения для подростков за 3 дня и показали его на демо-дне.",
    likes: 18,
    commentsCount: 6,
  },
  {
    id: "post-2",
    authorId: "u-roman",
    createdAt: "2024-02-13T14:30:00.000Z",
    type: "announcement",
    title: "Челлендж на неделю",
    content: "Кто успеет привлечь первых 5 лидов до воскресенья? Победителям — 80 XP и разбор.",
    likes: 22,
    commentsCount: 10,
  },
  {
    id: "post-3",
    authorId: "u-milena",
    clubId: "club-creative",
    createdAt: "2024-02-11T18:45:00.000Z",
    type: "progress",
    title: "Смонтировала первое портфолио",
    content: "Оформила кейсы в Notion и сделала мини-превью в CapCut. Кто хочет дать фидбек?",
    likes: 15,
    commentsCount: 4,
  },
  {
    id: "post-4",
    authorId: "u-sofia",
    createdAt: "2024-02-09T09:10:00.000Z",
    type: "story",
    title: "Как я закрыла свой первый тест",
    content: "Прописала гипотезы, сделала форму и получила 17 ответов. Теперь готовлю MVP.",
    likes: 9,
    commentsCount: 3,
  },
  {
    id: "post-5",
    authorId: "u-vera",
    clubId: "club-creative",
    createdAt: "2024-02-10T12:00:00.000Z",
    type: "achievement",
    title: "10 дней контент-серии",
    content: "Публиковала короткие заметки и видео ежедневно. Прирост 230 подписчиков.",
    likes: 12,
    commentsCount: 5,
  },
  {
    id: "post-6",
    authorId: "u-makar",
    clubId: "club-finance",
    createdAt: "2024-02-08T17:15:00.000Z",
    type: "announcement",
    title: "Созван по инвестициям",
    content: "В среду собираем Zoom про ETF и риски. Кому интересно — ставьте плюс.",
    likes: 11,
    commentsCount: 7,
  },
  {
    id: "post-7",
    authorId: "u-leo",
    createdAt: "2024-02-07T15:20:00.000Z",
    type: "progress",
    title: "Дописал лендинг для MVP",
    content: "Использовал готовый шаблон, собрал заявки через формы. CTR 6.4% — хочу улучшить копирайт.",
    likes: 8,
    commentsCount: 2,
  },
  {
    id: "post-8",
    authorId: "u-danila",
    createdAt: "2024-02-06T19:00:00.000Z",
    type: "achievement",
    title: "Собрал команду на игру",
    content: "Запустили мини-игру за 48 часов на джеме. 120 игроков за первый день!",
    likes: 14,
    commentsCount: 6,
  },
];

export const questions = [
  {
    id: "q-1",
    authorId: "u-alia",
    title: "Как собрать первых тестировщиков?",
    body: "Запускаю MVP и хочу 15–20 тестов от подростков. Какие каналы сработали у вас?",
    tags: ["стартап", "клиенты"],
    createdAt: "2024-02-12T09:00:00.000Z",
    upvotesCount: 18,
    bestAnswerId: "a-3",
  },
  {
    id: "q-2",
    authorId: "u-sofia",
    title: "Как не бояться первых продаж?",
    body: "Есть консультации по финансам, но страшно назначать цену. Какие шаги помогут?",
    tags: ["финансы", "первые клиенты"],
    createdAt: "2024-02-11T14:00:00.000Z",
    upvotesCount: 12,
  },
  {
    id: "q-3",
    authorId: "u-roman",
    title: "Чем измерять прогресс по треку?",
    body: "Собираю трек для клуба. Какие метрики и чекпоинты вы отслеживаете?",
    tags: ["трек", "метрики"],
    createdAt: "2024-02-10T10:30:00.000Z",
    upvotesCount: 10,
  },
  {
    id: "q-4",
    authorId: "u-milena",
    title: "Как организовать командный квест?",
    body: "Хотим запустить недельный спринт: сколько задач и как считать общий XP?",
    tags: ["команда", "мотивация"],
    createdAt: "2024-02-09T18:15:00.000Z",
    upvotesCount: 9,
  },
];

export const answers = [
  {
    id: "a-1",
    questionId: "q-1",
    authorId: "u-roman",
    body: "Запусти мини-форму + подарки: доступ к закрытому разбору или приоритет на фичи. Работают дискорд-сервера школ и офлайн-клубы.",
    createdAt: "2024-02-12T10:00:00.000Z",
    upvotesCount: 11,
  },
  {
    id: "a-2",
    questionId: "q-2",
    authorId: "u-vera",
    body: "Сделай три пакета: бесплатная диагностика, лайт-пакет и фулл. Начинай с честной минимальной цены и поднимай после 3 продаж.",
    createdAt: "2024-02-11T15:00:00.000Z",
    upvotesCount: 8,
  },
  {
    id: "a-3",
    questionId: "q-1",
    authorId: "u-milena",
    body: "Короткий лендинг + кнопка \"testers\". Проси друзей репостнуть, а в клубах делай пост с конкретной датой демо.",
    createdAt: "2024-02-12T11:00:00.000Z",
    upvotesCount: 14,
  },
  {
    id: "a-4",
    questionId: "q-3",
    authorId: "u-sofia",
    body: "На каждую главу трека ставим метрику: число попыток, % завершения, средний балл теста. Плюс еженедельный созвон по прогрессу.",
    createdAt: "2024-02-10T12:00:00.000Z",
    upvotesCount: 6,
  },
  {
    id: "a-5",
    questionId: "q-4",
    authorId: "u-roman",
    body: "Выберите 3–4 измеримых задачи на неделю и общий бэклог. Давать XP за каждый чекпоинт, а бонус — за общий результат команды.",
    createdAt: "2024-02-09T19:00:00.000Z",
    upvotesCount: 7,
  },
];

export const channels = [
  { id: "ch-global", name: "Общий чат", description: "Главные новости и быстрые вопросы", type: "global" },
  { id: "ch-finance", name: "Финансы", description: "Доходы, подушки, первые инвестиции", type: "topic" },
  { id: "ch-product", name: "Продукт и дизайн", description: "Прототипы, UI, исследования", type: "topic" },
  { id: "ch-teams", name: "Командные квесты", description: "Созвоны, договорённости и прогресс", type: "club" },
];

export const initialMessages = [
  {
    id: "m-1",
    channelId: "ch-global",
    authorId: "u-roman",
    body: "Ребята, привет! Делимся победами за неделю ✨",
    createdAt: "2024-02-13T07:30:00.000Z",
  },
  {
    id: "m-2",
    channelId: "ch-global",
    authorId: "u-alia",
    body: "Я закрыла дизайн-спринт, готова показать макеты в четверг!",
    createdAt: "2024-02-13T08:00:00.000Z",
  },
  {
    id: "m-3",
    channelId: "ch-product",
    authorId: "u-milena",
    body: "Кто может быстро посмотреть прототип? Нужно 10 минут фидбэка.",
    createdAt: "2024-02-12T16:00:00.000Z",
  },
  {
    id: "m-4",
    channelId: "ch-finance",
    authorId: "u-makar",
    body: "Залил табличку с учётом расходов. Добавил формулу для автоматического бюджета.",
    createdAt: "2024-02-12T19:10:00.000Z",
  },
];
